### ISSUE TITLE
No scripts

### ISSUE THREAD

**Issue by eggs-Johnson** [Ruturajn/Dotfiles#2]
Readme says that scripts for rofi and etc can be found inside of Arch-Setup-Scripts/. However that is not the case

**Comment by Ruturajn** [comment]
Hi,
I am not sure I understand your question, but here is the link for the [directory](https://github.com/Ruturajn/Dotfiles/tree/main/Arch-Setup-Scripts) that contains, both [Arch_Install.sh](https://github.com/Ruturajn/Dotfiles/blob/main/Arch-Setup-Scripts/Arch_Install.sh) and [Arch_Setup_Install.sh](https://github.com/Ruturajn/Dotfiles/blob/main/Arch-Setup-Scripts/Arch_Setup_Install.sh). These scripts will perform a base Arch-Linux Install, and then setup the rice respectively(Do read the [README.md](https://github.com/Ruturajn/Dotfiles/blob/main/Arch-Setup-Scripts/README.md) file before using the Arch_Install.sh script). As far as the utility scripts are concerned they are [here](https://github.com/Ruturajn/Dotfiles/tree/main/qtile/Scripts), and addressing the `README.md`, it says that this repo contains the **config** files, for rofi, qtile, fish, etc. and **scripts** for setting up this rice on Ubuntu and Arch-Linux.

Edit: Although, maybe the way I have written it in the `README` is a bit confusing, now that I look at it. So, I will update it. Thanks, and I do hope that you found what you were looking for, from the info given above.

**Comment by eggs-Johnson** [comment]
Those were the scripts I was looking for. Thank you!
