### ISSUE TITLE
power button not working in vm

### ISSUE THREAD

**Issue by aurkaxi** [Ruturajn/Dotfiles#4]
first i tried manual setup, i faced the issue and then tried setup script for arch, no solution.

i am talking about the far right button in top bar. i tried mod+ctrl+q keybind but power menu didn't show up. it just logged me out. but for the bar, it does nothing.

**Comment by Ruturajn** [comment]
Yeah, that is a bug in `qtile`, in the version that is pulled from `pacman`. Install the latest git version, from the _AUR_, that should solve it.
